<?php

return [
    'excluded_fields' => [
        'password',
        'remember_token',
        'created_at',
        'updated_at',
        'deleted_at',
        'photo',
        'avatar',
        'token',
        'api_token',
        'two_factor_secret',
        'two_factor_recovery_codes',
        'two_factor_confirmed_at',
        'email_verified_at',
        'image',
        'logo_path',
        'invoice_file_path',
        'invoice_file_name',
        'invoice_file_mime',
        'invoice_file_size',
        'identity_document_number_normalized',
        'phone_normalized',
    ],

    'foreign_keys' => [
        'customer_id' => \App\Models\Customer::class,
        'supplier_id' => \App\Models\Supplier::class,
        'product_id' => \App\Models\Product::class,
        'category_id' => \App\Models\Category::class,
        'user_id' => \App\Models\User::class,
        'purchase_order_id' => \App\Models\PurchaseOrder::class,
        'delivery_note_id' => \App\Models\DeliveryNote::class,
        'sale_id' => \App\Models\Sale::class,
        'quote_id' => \App\Models\Quote::class,
    ],

    'field_labels' => [
        'name' => 'Nom',
        'description' => 'Description',
        'sku' => 'SKU',
        'barcode' => 'Code-barres',
        'price' => 'Prix',
        'cost_price' => 'Prix d\'achat',
        'stock_quantity' => 'Stock',
        'stock' => 'Stock',
        'min_stock_level' => 'Stock minimum',
        'unit' => 'Unité',
        'location' => 'Emplacement',
        'is_active' => 'Actif',
        'category_id' => 'Catégorie',
        'expiration_date' => 'Date d\'expiration',
        'alert_threshold_value' => 'Seuil d\'alerte',
        'alert_threshold_unit' => 'Unité d\'alerte',
        'email' => 'Email',
        'phone' => 'Téléphone',
        'identity_document_type' => 'Type de pièce d\'identité',
        'identity_document_number' => 'Numéro de pièce d\'identité',
        'phone1' => 'Téléphone 1',
        'phone2' => 'Téléphone 2',
        'phone3' => 'Téléphone 3',
        'mobile' => 'Mobile',
        'address' => 'Adresse',
        'city' => 'Ville',
        'postal_code' => 'Code postal',
        'country' => 'Pays',
        'credit_limit' => 'Limite de crédit',
        'contact_person' => 'Personne de contact',
        'tax_id' => 'Identifiant fiscal',
        'notes' => 'Notes',
        'status' => 'Statut',
        'customer_id' => 'Client',
        'supplier_id' => 'Fournisseur',
        'product_id' => 'Produit',
        'user_id' => 'Utilisateur',
        'category_id' => 'Catégorie',
        'purchase_order_id' => 'Bon de commande',
        'delivery_note_id' => 'Bon de livraison',
        'sale_id' => 'Vente',
        'quote_id' => 'Devis',
        'po_number' => 'N° bon de commande',
        'delivery_number' => 'N° bon de livraison',
        'sale_number' => 'N° facture',
        'quote_number' => 'N° devis',
        'order_date' => 'Date de commande',
        'expected_delivery_date' => 'Date de livraison prévue',
        'delivery_date' => 'Date de livraison',
        'subtotal' => 'Sous-total',
        'tax_amount' => 'Montant TVA',
        'discount_amount' => 'Remise',
        'total_amount' => 'Montant total',
        'down_payment_amount' => 'Acompte',
        'remaining_amount' => 'Reste à payer',
        'payment_status' => 'Statut de paiement',
        'payment_method' => 'Mode de paiement',
        'due_date' => 'Date d\'échéance',
        'sale_date' => 'Date de vente',
        'quote_date' => 'Date du devis',
        'valid_until' => 'Valide jusqu\'au',
        'invoice_number' => 'N° facture fournisseur',
        'quantity' => 'Quantité',
        'unit_price' => 'Prix unitaire',
        'total_price' => 'Prix total',
        'role' => 'Rôle',
        'tagline' => 'Slogan',
        'website' => 'Site web',
        'rc_number' => 'N° RC',
        'ncc_number' => 'N° NCC',
        'title' => 'Titre',
        'amount' => 'Montant',
        'category' => 'Catégorie',
        'expense_number' => 'N° dépense',
        'expense_date' => 'Date de dépense',
        'receipt_number' => 'N° reçu',
        'vendor' => 'Fournisseur',
        'color' => 'Couleur',
        'deleted_at' => 'Date de suppression',
    ],

    'enum_labels' => [
        'status' => [
            'draft' => 'Brouillon',
            'sent' => 'Envoyé',
            'confirmed' => 'Confirmé',
            'partially_received' => 'Partiellement reçu',
            'received' => 'Reçu',
            'cancelled' => 'Annulé',
            'pending' => 'En attente',
            'validated' => 'Validé',
            'completed' => 'Terminé',
            'active' => 'Actif',
            'inactive' => 'Inactif',
            'paid' => 'Payé',
            'partial' => 'Partiel',
            'pending_payment' => 'En attente',
        ],
        'payment_status' => [
            'paid' => 'Payé',
            'partial' => 'Partiel',
            'pending' => 'En attente',
        ],
        'payment_method' => [
            'cash' => 'Espèces',
            'card' => 'Carte bancaire',
            'bank_transfer' => 'Virement bancaire',
            'credit_card' => 'Carte de crédit',
            'mobile_money' => 'Mobile Money',
            'check' => 'Chèque',
            'orange_money' => 'Orange Money',
            'wave' => 'Wave',
        ],
        'category' => [
            'fournitures' => 'Fournitures',
            'equipement' => 'Équipement',
            'marketing' => 'Marketing',
            'transport' => 'Transport',
            'formation' => 'Formation',
            'maintenance' => 'Maintenance',
            'utilities' => 'Services publics',
            'autres' => 'Autres',
        ],
        'role' => [
            'admin' => 'Administrateur',
            'user' => 'Utilisateur',
            'vendeur' => 'Vendeur',
            'gestionnaire' => 'Gestionnaire',
        ],
        'identity_document_type' => [
            'national_id' => 'Carte d\'identité',
            'passport' => 'Passeport',
            'other' => 'Autre',
        ],
    ],

    'masked_fields' => [
        'identity_document_number',
    ],
];
